global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Diagnostics;
global using Microsoft.Extensions.DependencyInjection;
global using Algorithms.Data;
global using Algorithms.ProblemSolver.App;
